# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 91))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_selection_photos = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_selection_photos.setGeometry(QtCore.QRect(10, 20, 231, 23))
        self.pushButton_selection_photos.setObjectName("pushButton_selection_photos")
        self.pushButton_selection_dossier_export = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_selection_dossier_export.setGeometry(QtCore.QRect(250, 20, 231, 23))
        self.pushButton_selection_dossier_export.setObjectName("pushButton_selection_dossier_export")
        self.label_info_init = QtWidgets.QLabel(self.groupBox)
        self.label_info_init.setGeometry(QtCore.QRect(10, 50, 231, 31))
        self.label_info_init.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_init.setObjectName("label_info_init")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(250, 50, 231, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAcceptDrops(False)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 241, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_multi_process = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_multi_process.setGeometry(QtCore.QRect(10, 70, 158, 17))
        self.checkBox_multi_process.setObjectName("checkBox_multi_process")
        self.checkBox_pdf = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_pdf.setGeometry(QtCore.QRect(10, 46, 158, 17))
        self.checkBox_pdf.setObjectName("checkBox_pdf")
        self.checkBox_jpg = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_jpg.setGeometry(QtCore.QRect(10, 22, 158, 17))
        self.checkBox_jpg.setObjectName("checkBox_jpg")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 491, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(10, 80, 471, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_info_conversion = QtWidgets.QLabel(self.groupBox_3)
        self.label_info_conversion.setGeometry(QtCore.QRect(10, 51, 471, 21))
        self.label_info_conversion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_conversion.setObjectName("label_info_conversion")
        self.pushButton_lancement_conversion = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_lancement_conversion.setGeometry(QtCore.QRect(10, 22, 471, 23))
        self.pushButton_lancement_conversion.setObjectName("pushButton_lancement_conversion")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(260, 110, 241, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_DPI = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_DPI.setGeometry(QtCore.QRect(130, 30, 101, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_DPI.setFont(font)
        self.lineEdit_DPI.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DPI.setClearButtonEnabled(True)
        self.lineEdit_DPI.setObjectName("lineEdit_DPI")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.lineEdit_largeur = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_largeur.setGeometry(QtCore.QRect(130, 70, 101, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_largeur.setFont(font)
        self.lineEdit_largeur.setToolTip("")
        self.lineEdit_largeur.setInputMask("")
        self.lineEdit_largeur.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_largeur.setClearButtonEnabled(True)
        self.lineEdit_largeur.setObjectName("lineEdit_largeur")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Initialisation"))
        self.pushButton_selection_photos.setText(_translate("MainWindow", "Selection des photos à convertir"))
        self.pushButton_selection_dossier_export.setText(_translate("MainWindow", "Selection du dossier d\'exportation"))
        self.label_info_init.setText(_translate("MainWindow", "Veuiller sélectionner les photos à convertir"))
        self.label.setText(_translate("MainWindow", "Un sous dossier \'export\' sera créé automatiquement dans le dossier sélectionné"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Options"))
        self.checkBox_multi_process.setText(_translate("MainWindow", "Multi-process"))
        self.checkBox_pdf.setText(_translate("MainWindow", "Convertir en .pdf"))
        self.checkBox_jpg.setText(_translate("MainWindow", "Convertir en .jpg"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Conversion"))
        self.label_info_conversion.setText(_translate("MainWindow", "informations convertion"))
        self.pushButton_lancement_conversion.setText(_translate("MainWindow", "Lancement de la convertion"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Réglages"))
        self.lineEdit_DPI.setText(_translate("MainWindow", "300"))
        self.label_2.setText(_translate("MainWindow", "DPI"))
        self.label_3.setText(_translate("MainWindow", "Dimension max. image finale (cm)"))
        self.lineEdit_largeur.setText(_translate("MainWindow", "21"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))

